### PR TITLE
NDT-369 Styling the homepage.

### PR DESCRIPTION
**Pull request by wansooseo**
1. Create three custom blocks for the homepage.
homepage-blocks

2. Enable three blocks on the main content area in that order.
3. Here is the code snippet for each block.

**Homepage Hero Image**
```
<header class="homepage__hero">
<div class="homepage__text--container">
<div class="container">
<div class="row">
<div class="col-md-6 col-sm-8 col-xs-12">
<h1>Help More Patients Quit Smoking with Digital Cessation Tools</h1>

<p>As a product of the Cancer Center Cessation Initiative (C3I), this toolkit was developed to help all cancer care professionals across the United States implement or enhance tobacco treatment programs for patients, survivors, and their loved ones.</p>

<p>Here you can find evidence-based digital cessation tools and guidance documents that address common approaches, challenges, and strategies faced by cancer centers working in tobacco cessation.</p>
<a class="btn btn-primary" href="https://cessationtoolkit.cancer.gov/how-to-use-the-toolkit" role="button">HOW TO USE THE TOOLKIT</a></div>
</div>
</div>
</div>
</header>
```

**Homepage Hero Image**
```
<div class="row what-can-you-do-here__container justify-content-xs-center">
<div class="col-lg-12 what-can-you-do-here__container title">
<h2>WHAT CAN YOU DO HERE?</h2>
</div>

<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 col-center-block what-can-you-do-here__wrapper"><img class="icon" src="themes/custom/digital_toolkit/src/images/shape-2x.svg" />
<h3>Discocer</h3>

<p>Discover different types of digital tobacco cessation tools to use with patients and find out which cancer centers are using them.</p>
</div>

<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 col-center-block what-can-you-do-here__wrapper"><img class="icon" src="themes/custom/digital_toolkit/src/images/group-4-2x.svg" />
<h3>Browse</h3>

<p>Browse C3I cancer centers’ profiles and learn what they are doing to ensure that all cancer patients who use tobacco are receiving help to quit.</p>
</div>

<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 col-center-block what-can-you-do-here__wrapper"><img class="icon" src="themes/custom/digital_toolkit/src/images/book-01-2x.svg" />
<h3>Read</h3>

<p>Read guidance documents to gain insights for enhancing cessation programs and digital tools and addressing common implementation challenges.</p>
</div>
</div>
```

**Homepage Main Content**
```
<div class="homepage-three-category__container">
<div class="container">
<h2>Digital Cessation Tools</h2>

<div class="row each-category">
<div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
<p>Digital cessation tools—such as websites, text programs, and smartphone apps—may improve tobacco cessation rates and increase patients’ access to cessation programs. Explore these tools to find out which ones meet the needs of your treatment program and your patients.</p>
</div>

<div class="col-lg-4 col-md-12 col-sm-12 col-xs-12"><a class="btn btn-primary" href="https://cessationtoolkit.cancer.gov/digital-cessation-tools" role="button">SEE ALL DIGITAL TOOLS</a></div>
</div>

<h2>Cancer Center Directory</h2>

<div class="row each-category">
<div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
<p>The National Cancer Institute (NCI) selected 42 cancer centers to participate in the Cancer Center Cessation Initiative (C3I). The aim of C3I is to help cancer centers build and implement sustainable tobacco cessation treatment programs. Explore what these cancer centers are doing to help patients quit tobacco.</p>
</div>

<div class="col-lg-4 col-md-12 col-sm-12 col-xs-12"><a class="btn btn-primary" href="https://cessationtoolkit.cancer.gov/cancer-center-directory" role="button">SEE ALL CANCER CENTERS</a></div>
</div>

<h2>Guidance Documents</h2>

<div class="row each-category">
<div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
<p>Use this collection of guides, case studies, and additional information to gain insights into common challenges and needs of cancer centers as they implement tobacco cessation programs for their patients.</p>
</div>

<div class="col-lg-4 col-md-12 col-sm-12 col-xs-12"><a class="btn btn-primary" href="https://cessationtoolkit.cancer.gov/cancer-center-directory" role="button">SEE ALL GUIDANCE DOCUMENTS</a></div>
</div>
</div>
</div>
```

4. Flush all cashes
5. Enjoy the homepage view.
**This is mostly for the desktop and the mobile viewports**

### CODE REVIEW

**Comment by lebeza** [comment]
There is a conflict

**Comment by lebeza** [comment]
@wansooseo i still see the image hero problem and the bottom white space issue

image

image

**Comment by lebeza** [comment]
also, the hero image image .homepage__hero::before style is creating an overflow on mobile view 

image

**Comment by wansooseo** [comment]
@lebeza Please review `organization.scss` in `style.scss` so we can remove the `page` section. There is two `organization.scss` and not sure which one is the most updated one.

**Comment by lebeza** [comment]
@wansooseo please remove the one in the pages folder. the correct one is the one in the components folder

**Comment by wansooseo** [comment]
> @wansooseo please remove the one in the pages folder. the correct one is the one in the components folder

@lebeza Completed.

**Comment by lebeza** [comment]
@wansooseo 
- do we need /home in all the blocks because i see the homepage blocks in org and product landing and detail pages 
image

The black background still looks off on big screens. I don't know if anyone sees the site on big screens. Did you try to make the width % rather than px?

image

**Comment by shashank-naik** [comment]
> @wansooseo
> 
> * do we need /home in all the blocks because i see the homepage blocks in org and product landing and detail pages
>   image
> 
> The black background still looks off on big screens. I don't know if anyone sees the site on big screens. Did you try to make the width % rather than px?
> 
> image

The blocks should only be displayed on the homepage. This can be done in the Drupal UI. See my [comment](https://jira.icfwebservices.com/secure/EditComment!default.jspa?id=175928&commentId=502467) in the ticket

**Comment by lebeza** [comment]
looks good to me. Merging to stage

**Pull request merged**
